# Generated by Django 4.1.4 on 2022-12-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentuser',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentuser',
            name='payment_date',
            field=models.DateField(null=True),
        ),
    ]
