# Generated by Django 4.1.4 on 2022-12-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_paymentuser_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='logo',
            field=models.ImageField(null=True, upload_to='logo'),
        ),
    ]
